In [64]:
import pandas as pd
import numpy as np
df=pd.read_csv(r'C:\Users\M S I\Desktop\5thsem_OJT\project1_diabetes\data\processed\project1_diabetes_cleaned.csv',parse_dates=["last_checkup_date"])

In [65]:
df.head(10)

,patient_id,age,gender,pregnancies,glucose,blood_pressure,skin_thickness,insulin,bmi,diabetes_pedigree,physical_activity,smoker,last_checkup_date,outcome
0,P00826,79,male,0,124.0,71.0,30.0,124.0,23.4,0.588,Unknown,NO,2023-04-20,0
1,P00108,37,male,0,153.0,85.0,24.0,42.0,33.9,0.192,Medium,YES,2024-05-03,1
2,P00517,39,female,0,142.0,68.0,22.0,159.0,26.9,0.777,Low,UNKNOWN,2023-07-08,0
3,P00687,68,female,7,121.0,88.0,26.0,124.0,29.0,1.217,Unknown,YES,2024-04-14,1
4,P00927,75,female,0,107.0,84.0,31.0,101.0,21.2,0.278,Low,NO,2024-01-27,0
5,P00755,37,female,0,145.0,80.0,26.0,124.0,22.0,0.488,High,YES,2024-01-10,0
6,P00431,58,male,5,95.0,72.0,26.0,170.0,27.2,0.197,High,NO,2023-12-25,0
7,P00542,58,female,3,150.0,68.0,17.0,124.0,46.0,0.808,Medium,NO,2024-06-20,1
8,P00929,32,female,6,129.0,74.0,26.0,226.0,20.6,0.655,High,UNKNOWN,2023-10-15,1
9,P00513,61,female,0,161.0,77.0,35.0,201.0,35.0,1.229,Medium,YES,2023-12-22,1

In [66]:
df.dtypes

patient_id                      str
age                           int64
gender                          str
pregnancies                   int64
glucose                     float64
blood_pressure              float64
skin_thickness              float64
insulin                     float64
bmi                         float64
diabetes_pedigree           float64
physical_activity               str
smoker                          str
last_checkup_date    datetime64[us]
outcome                       int64
dtype: object

In [67]:
df.shape

(950, 14)

CREATE NEW COLUMN AGE BAND

In [68]:
df['age_band']=pd.cut(df['age'], 
bins=[0, 35, 55, 120],
 labels=['under 35', '35-55', 'over 55'])

In [69]:
df.head()

,patient_id,age,gender,pregnancies,glucose,blood_pressure,skin_thickness,insulin,bmi,diabetes_pedigree,physical_activity,smoker,last_checkup_date,outcome,age_band
0,P00826,79,male,0,124.0,71.0,30.0,124.0,23.4,0.588,Unknown,NO,2023-04-20,0,over 55
1,P00108,37,male,0,153.0,85.0,24.0,42.0,33.9,0.192,Medium,YES,2024-05-03,1,35-55
2,P00517,39,female,0,142.0,68.0,22.0,159.0,26.9,0.777,Low,UNKNOWN,2023-07-08,0,35-55
3,P00687,68,female,7,121.0,88.0,26.0,124.0,29.0,1.217,Unknown,YES,2024-04-14,1,over 55
4,P00927,75,female,0,107.0,84.0,31.0,101.0,21.2,0.278,Low,NO,2024-01-27,0,over 55

CREATE A BMI CATEGORY FEATURE

In [70]:
df['bmi_category']=pd.cut(df['bmi'],
     bins=[0,18.5,25,30,100],
      labels=['underweight','normal','overweight','obese'])

In [71]:
df['bmi_category']. value_counts()

bmi_category
obese          553
overweight     235
normal         124
underweight     38
Name: count, dtype: int64

CREATE A GLUCOSE BAND FEATURE

In [72]:
df['glucose_category']=pd.cut(df['glucose'],
bins=[0,100,126,300],
labels=['normal','prediabetic','diabetes'])

In [73]:
df['glucose_category']. value_counts()

glucose_category
diabetes       349
prediabetic    337
normal         264
Name: count, dtype: int64

CREATE A INSULIN-GLUCOSE RATIO FEATURE

In [74]:
df['insulin_glucose_ratio']=df['insulin']/df['glucose']

In [75]:
df['insulin_glucose_ratio'].head()

0    1.000000
1    0.274510
2    1.119718
3    1.024793
4    0.943925
Name: insulin_glucose_ratio, dtype: float64

In [76]:
df['insulin_glucose_ratio'].describe()

count    950.000000
mean       1.213108
std        1.179183
min        0.054348
25%        0.726708
50%        1.052139
75%        1.512831
max       22.745763
Name: insulin_glucose_ratio, dtype: float64

CHECK RATIO FOR IMPOSSIBLE VALUES

In [77]:
df['insulin_glucose_ratio'].describe()
np.isinf(df['insulin_glucose_ratio']).sum()

np.int64(0)

CREATE A PREGNANCIES_PER_YEAR OF AGE FEATURE

In [78]:
df['pregnancy_rate']=df['pregnancies']/df['age']

In [79]:
df.describe()

,age,pregnancies,glucose,blood_pressure,skin_thickness,insulin,bmi,diabetes_pedigree,last_checkup_date,outcome,insulin_glucose_ratio,pregnancy_rate
count,950.000000,950.000000,950.000000,950.000000,950.000000,950.000000,950.000000,950.000000,950,950.000000,950.000000,950.000000
mean,49.864211,1.853684,117.866257,72.229474,26.277895,131.748421,31.394105,0.461863,2024-01-08 00:45:28.421052,0.287368,1.213108,0.042787
min,21.000000,0.000000,50.000000,40.000000,5.000000,10.000000,15.000000,0.050000,2023-01-03 00:00:00,0.000000,0.054348,0.000000
25%,35.000000,0.000000,98.000000,65.000000,21.000000,91.000000,26.800000,0.244250,2023-07-15 00:00:00,0.000000,0.726708,0.000000
50%,50.000000,0.000000,117.855165,72.000000,26.000000,124.000000,31.100000,0.445500,2024-01-11 00:00:00,0.000000,1.052139,0.000000
75%,65.000000,4.000000,136.000000,79.750000,31.000000,160.000000,35.275000,0.654750,2024-07-09 06:00:00,1.000000,1.512831,0.072661
max,81.000000,8.000000,215.000000,107.000000,67.000000,1399.000000,94.500000,1.532000,2024-12-28 00:00:00,1.000000,22.745763,0.380952
std,17.487840,2.622080,28.057794,11.520723,8.945134,102.018980,8.162011,0.285111,NaN,0.452773,1.179183,0.067440

CREATE A DAYS SINCE LAST CHECKUP FEATURE

In [80]:
reference_date=df['last_checkup_date'].max()

In [81]:
reference_date

Timestamp('2024-12-28 00:00:00')

In [82]:
df['days_since_checkup']= (reference_date - df['last_checkup_date']).dt.days

In [83]:
df['days_since_checkup'].head()

0    618
1    239
2    539
3    258
4    336
Name: days_since_checkup, dtype: int64

CREATE A CATEGORICAL COMBINATION FEATURE

In [84]:
df['activity_smoker']=df['physical_activity']+'/'+df['smoker']

CHECK THE COMBINATION FEATURE'S BALANCE

In [85]:
df['activity_smoker'].value_counts()

activity_smoker
Medium/NO          207
High/NO            195
Low/NO             180
Low/YES             93
Medium/YES          90
High/YES            85
Unknown/NO          36
High/UNKNOWN        22
Unknown/YES         17
Medium/UNKNOWN      12
Low/UNKNOWN          9
Unknown/UNKNOWN      4
Name: count, dtype: int64

In [86]:
# activity smoker = physical_activity + smoker
# age band = age
# bmi category = bmi
# glucose category = glucose
# insulin glucose ratio = insulin/glucose
# pregnancy rate = pregnancies/age
# days since checkup = reference_date - last_checkup_date

In [88]:
df.shape

(950, 21)